export interface Position {
  x: number;
  y: number;
}

export type NodeStatus = 'idle' | 'running' | 'completed' | 'error';

export interface AgentNode {
  id: string;
  position: Position;
  data: {
    label: string;
    systemInstruction: string;
    input: string; // The data received from previous node or initial input
    output: string; // The data generated by this node
    status: NodeStatus;
    errorMessage?: string;
  };
}

export interface Connection {
  id: string;
  source: string; // Source Node ID
  target: string; // Target Node ID
}

export interface DragState {
  isDragging: boolean;
  nodeId: string | null;
  offset: Position;
}

export interface ConnectionState {
  isConnecting: boolean;
  sourceNodeId: string | null;
  mousePos: Position;
}